insert into State (code, name, country) values ( 'AL','Alabama','USA');
insert into State (code, name, country) values ( 'AK','Alaska','USA');
insert into State (code, name, country) values ( 'AZ','Arizona','USA');
insert into State (code, name, country) values ( 'AR','Arkansas','USA');
insert into State (code, name, country) values ( 'CA','California','USA');
insert into State (code, name, country) values ( 'CO','Colorado','USA');
insert into State (code, name, country) values ( 'CT','Connecticut','USA');
insert into State (code, name, country) values ( 'DE','Delaware','USA');
insert into State (code, name, country) values ( 'FL','Florida','USA');
insert into State (code, name, country) values ( 'GA','Georgia','USA');
insert into State (code, name, country) values ( 'HI','Hawaii','USA');
insert into State (code, name, country) values ( 'ID','Idaho','USA');
insert into State (code, name, country) values ( 'IL','Illinois','USA');
insert into State (code, name, country) values ( 'IN','Indiana','USA');
insert into State (code, name, country) values ( 'KS','Kansas','USA');
insert into State (code, name, country) values ( 'KY','Kentucky','USA');
insert into State (code, name, country) values ( 'LA','Louisiana','USA');
insert into State (code, name, country) values ( 'ME','Maine','USA');
insert into State (code, name, country) values ( 'MD','Maryland','USA');
insert into State (code, name, country) values ( 'MA','Massachusetts','USA');
insert into State (code, name, country) values ( 'MN','Minnesota','USA');
insert into State (code, name, country) values ( 'MS','Mississippi','USA');
insert into State (code, name, country) values ( 'MO','Missouri','USA');
insert into State (code, name, country) values ( 'MT','Montana','USA');
insert into State (code, name, country) values ( 'NE','Nebraska','USA');
insert into State (code, name, country) values ( 'NV','Nevada','USA');
insert into State (code, name, country) values ( 'NH','New Hampshire','USA');
insert into State (code, name, country) values ( 'NJ','New Jersey','USA');
insert into State (code, name, country) values ( 'NM','New Mexico','USA');
insert into State (code, name, country) values ( 'NY','New York','USA');
insert into State (code, name, country) values ( 'NC','North Carolina','USA');
insert into State (code, name, country) values ( 'OH','Ohio','USA');
insert into State (code, name, country) values ( 'OR','Oregon','USA');
insert into State (code, name, country) values ( 'PA','Pennsylvania','USA');
insert into State (code, name, country) values ( 'RI','Rhode Island','USA');
insert into State (code, name, country) values ( 'SC','South Carolina','USA');
insert into State (code, name, country) values ( 'TN','Tennessee','USA');
insert into State (code, name, country) values ( 'TX','Texas','USA');
insert into State (code, name, country) values ( 'UT','Utah','USA');
insert into State (code, name, country) values ( 'VT','Vermont','USA');
insert into State (code, name, country) values ( 'VA','Virginia','USA');
insert into State (code, name, country) values ( 'WV','West Virginia','USA');
insert into State (code, name, country) values ( 'WI','Wisconsin','USA');
insert into State (code, name, country) values ( 'AB','Alberta','CAN');
insert into State (code, name, country) values ( 'BC','British Colombia','CAN');
insert into State (code, name, country) values ( 'DR','Dominican Republic','USA');
insert into State (code, name, country) values ( 'MX','Mexico','MEX');
insert into State (code, name, country) values ( 'NB','New Brunswick','CAN');
insert into State (code, name, country) values ( 'NF','New Founland','CAN');
insert into State (code, name, country) values ( 'NS','Nova Scotia','CAN');
insert into State (code, name, country) values ( 'ON','Ontario','CAN');
insert into State (code, name, country) values ( 'PE','Prince Edward Island','CAN');
insert into State (code, name, country) values ( 'PQ','Quebec','CAN');
insert into State (code, name, country) values ( 'PR','Puerto Rico','USA');
insert into State (code, name, country) values ( 'DF','Mexico City','MEX');
insert into State (code, name, country) values ( 'NA','Tepic','MEX');
insert into State (code, name, country) values ( 'GT','Celaya','MEX');
insert into State (code, name, country) values ( 'PU','Puebla','MEX');
insert into State (code, name, country) values ( 'YA','Merida','MEX');
insert into State (code, name, country) values ( 'SN','Guaymas','MEX');
insert into State (code, name, country) values ( 'BA','Bahamas','USA');
insert into State (code, name, country) values ( 'AP','Army Pacific','USA');
insert into State (code, name, country) values ( 'AA','Army Americas','USA');
insert into State (code, name, country) values ( 'PB','Puebla','MEX');
insert into State (code, name, country) values ( 'AG','Aguascallentes','MEX');
insert into State (code, name, country) values ( 'BN','Baja California Norte','MEX');
insert into State (code, name, country) values ( 'CI','Colima','MEX');
insert into State (code, name, country) values ( 'CP','Coahuila','MEX');
insert into State (code, name, country) values ( 'DU','Durango','MEX');
insert into State (code, name, country) values ( 'HD','Hildago','MEX');
insert into State (code, name, country) values ( 'MC','Michoacan','MEX');
insert into State (code, name, country) values ( 'MR','Morelos','MEX');
insert into State (code, name, country) values ( 'NL','Nuevo Leon','MEX');
insert into State (code, name, country) values ( 'OX','Oaxaca','MEX');
insert into State (code, name, country) values ( 'QT','Queretaro','MEX');
insert into State (code, name, country) values ( 'QR','Quintana Roo','MEX');
insert into State (code, name, country) values ( 'SL','San Luis Potosl','MEX');
insert into State (code, name, country) values ( 'TA','Tamaulipas','MEX');
insert into State (code, name, country) values ( 'TB','Tabasco','MEX');
insert into State (code, name, country) values ( 'TL','Tlaxcala','MEX');
insert into State (code, name, country) values ( 'YC','Yucatan','MEX');
insert into State (code, name, country) values ( 'ZA','Zacatecas','MEX');
insert into State (code, name, country) values ( 'AE','Army European','USA');
insert into State (code, name, country) values ( 'GU','Guam','USA');
insert into State (code, name, country) values ( 'JA','Jalisco','MEX');
insert into State (code, name, country) values ( 'NT','Northwest Territory','CAN');
insert into State (code, name, country) values ( 'SI','Sinaloa','MEX');
insert into State (code, name, country) values ( 'YT','Yukon Territory','CAN');
insert into State (code, name, country) values ( 'AS','American Samoa','USA');
insert into State (code, name, country) values ( 'CN','CAOVRLYFLG','USA');
insert into State (code, name, country) values ( 'GJ','Guanajuato','MEX');
insert into State (code, name, country) values ( 'SD','South Dakota','USA');
insert into State (code, name, country) values ( 'WA','Washington','USA');
insert into State (code, name, country) values ( 'MB','Manitoba','CAN');
insert into State (code, name, country) values ( 'VI','Virgin Islands','USA');
insert into State (code, name, country) values ( 'BI','Bahamas','MEX');
insert into State (code, name, country) values ( 'GR','Guerrero','MEX');
insert into State (code, name, country) values ( 'SO','Sonora','MEX');
insert into State (code, name, country) values ( 'BS','Baja California Sur','MEX');
insert into State (code, name, country) values ( 'IA','Iowa','USA');
insert into State (code, name, country) values ( 'OK','Oklahoma','USA');
insert into State (code, name, country) values ( 'DC','District of Columbia','USA');
insert into State (code, name, country) values ( 'MI','Michigan','USA');
insert into State (code, name, country) values ( 'ND','North Dakota','USA');
insert into State (code, name, country) values ( 'WY','Wyoming','USA');
insert into State (code, name, country) values ( 'SK','Sasketchewan','CAN');
insert into State (code, name, country) values ( 'CS','Chiapas','MEX');
insert into State (code, name, country) values ( 'VE','Veracruz','MEX');
