insert into State (code, name, country, tax_rate) values ( 'AL','Alabama','US',0);
insert into State (code, name, country, tax_rate) values ( 'AK','Alaska','US',0);
insert into State (code, name, country, tax_rate) values ( 'AZ','Arizona','US',0);
insert into State (code, name, country, tax_rate) values ( 'AR','Arkansas','US',0);
insert into State (code, name, country, tax_rate) values ( 'CA','California','US',0);
insert into State (code, name, country, tax_rate) values ( 'CO','Colorado','US',0);
insert into State (code, name, country, tax_rate) values ( 'CT','Connecticut','US',0);
insert into State (code, name, country, tax_rate) values ( 'DE','Delaware','US',0);
insert into State (code, name, country, tax_rate) values ( 'FL','Florida','US',0);
insert into State (code, name, country, tax_rate) values ( 'GA','Georgia','US',0);
insert into State (code, name, country, tax_rate) values ( 'HI','Hawaii','US',0);
insert into State (code, name, country, tax_rate) values ( 'ID','Idaho','US',0);
insert into State (code, name, country, tax_rate) values ( 'IL','Illinois','US',0);
insert into State (code, name, country, tax_rate) values ( 'IN','Indiana','US',0);
insert into State (code, name, country, tax_rate) values ( 'KS','Kansas','US',0);
insert into State (code, name, country, tax_rate) values ( 'KY','Kentucky','US',0);
insert into State (code, name, country, tax_rate) values ( 'LA','Louisiana','US',0);
insert into State (code, name, country, tax_rate) values ( 'ME','Maine','US',0);
insert into State (code, name, country, tax_rate) values ( 'MD','Maryland','US',0);
insert into State (code, name, country, tax_rate) values ( 'MA','Massachusetts','US',0);
insert into State (code, name, country, tax_rate) values ( 'MN','Minnesota','US',0);
insert into State (code, name, country, tax_rate) values ( 'MS','Mississippi','US',0);
insert into State (code, name, country, tax_rate) values ( 'MO','Missouri','US',0);
insert into State (code, name, country, tax_rate) values ( 'MT','Montana','US',0);
insert into State (code, name, country, tax_rate) values ( 'NE','Nebraska','US',0);
insert into State (code, name, country, tax_rate) values ( 'NV','Nevada','US',0);
insert into State (code, name, country, tax_rate) values ( 'NH','New Hampshire','US',0);
insert into State (code, name, country, tax_rate) values ( 'NJ','New Jersey','US',0);
insert into State (code, name, country, tax_rate) values ( 'NM','New Mexico','US',0);
insert into State (code, name, country, tax_rate) values ( 'NY','New York','US',0);
insert into State (code, name, country, tax_rate) values ( 'NC','North Carolina','US',0);
insert into State (code, name, country, tax_rate) values ( 'OH','Ohio','US',0);
insert into State (code, name, country, tax_rate) values ( 'OR','Oregon','US',0);
insert into State (code, name, country, tax_rate) values ( 'PA','Pennsylvania','US',0);
insert into State (code, name, country, tax_rate) values ( 'RI','Rhode Island','US',0);
insert into State (code, name, country, tax_rate) values ( 'SC','South Carolina','US',0);
insert into State (code, name, country, tax_rate) values ( 'TN','Tennessee','US',0);
insert into State (code, name, country, tax_rate) values ( 'TX','Texas','US',0);
insert into State (code, name, country, tax_rate) values ( 'UT','Utah','US',0);
insert into State (code, name, country, tax_rate) values ( 'VT','Vermont','US',0);
insert into State (code, name, country, tax_rate) values ( 'VA','Virginia','US',0);
insert into State (code, name, country, tax_rate) values ( 'WV','West Virginia','US',0);
insert into State (code, name, country, tax_rate) values ( 'WI','Wisconsin','US',0);
insert into State (code, name, country, tax_rate) values ( 'AB','Alberta','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'BC','British Colombia','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'DR','Dominican Republic','US',0);
insert into State (code, name, country, tax_rate) values ( 'MX','Mexico','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'NB','New Brunswick','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'NF','New Founland','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'NS','Nova Scotia','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'ON','Ontario','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'PE','Prince Edward Island','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'PQ','Quebec','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'PR','Puerto Rico','US',0);
insert into State (code, name, country, tax_rate) values ( 'DF','Mexico City','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'NA','Tepic','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'GT','Celaya','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'PU','Puebla','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'YA','Merida','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'SN','Guaymas','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'BA','Bahamas','US',0);
insert into State (code, name, country, tax_rate) values ( 'AP','Army Pacific','US',0);
insert into State (code, name, country, tax_rate) values ( 'AA','Army Americas','US',0);
insert into State (code, name, country, tax_rate) values ( 'PB','Puebla','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'AG','Aguascallentes','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'BN','Baja California Norte','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'CI','Colima','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'CP','Coahuila','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'DU','Durango','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'HD','Hildago','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'MC','Michoacan','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'MR','Morelos','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'NL','Nuevo Leon','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'OX','Oaxaca','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'QT','Queretaro','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'QR','Quintana Roo','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'SL','San Luis Potosl','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'TA','Tamaulipas','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'TB','Tabasco','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'TL','Tlaxcala','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'YC','Yucatan','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'ZA','Zacatecas','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'AE','Army European','US',0);
insert into State (code, name, country, tax_rate) values ( 'GU','Guam','US',0);
insert into State (code, name, country, tax_rate) values ( 'JA','Jalisco','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'NT','Northwest Territory','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'SI','Sinaloa','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'YT','Yukon Territory','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'AS','American Samoa','US',0);
insert into State (code, name, country, tax_rate) values ( 'CN','CAOVRLYFLG','US',0);
insert into State (code, name, country, tax_rate) values ( 'GJ','Guanajuato','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'SD','South Dakota','US',0);
insert into State (code, name, country, tax_rate) values ( 'WA','Washington','US',8.4);
insert into State (code, name, country, tax_rate) values ( 'MB','Manitoba','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'VI','Virgin Islands','US',0);
insert into State (code, name, country, tax_rate) values ( 'BI','Bahamas','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'GR','Guerrero','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'SO','Sonora','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'BS','Baja California Sur','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'IA','Iowa','US',0);
insert into State (code, name, country, tax_rate) values ( 'OK','Oklahoma','US',0);
insert into State (code, name, country, tax_rate) values ( 'DC','District of Columbia','US',0);
insert into State (code, name, country, tax_rate) values ( 'MI','Michigan','US',0);
insert into State (code, name, country, tax_rate) values ( 'ND','North Dakota','US',0);
insert into State (code, name, country, tax_rate) values ( 'WY','Wyoming','US',0);
insert into State (code, name, country, tax_rate) values ( 'SK','Sasketchewan','CAN',0);
insert into State (code, name, country, tax_rate) values ( 'CS','Chiapas','MEX',0);
insert into State (code, name, country, tax_rate) values ( 'VE','Veracruz','MEX',0);
